### ISSUE TITLE
config-settings.php - not found error

### ISSUE THREAD

**Issue by yuvraj131** [jethrocarr/amberdms-bs#7]
![pioneer](https://cloud.githubusercontent.com/assets/5370661/12150965/a470df56-b4d2-11e5-8c4e-99916c80bbdc.JPG)
this is the message we are getting on first time page visit:

Warning: include(config-settings.php): failed to open stream: No such file or directory in /home/pioneerw/public_html/client/include/config.php on line 57

Warning: include(config-settings.php): failed to open stream: No such file or directory in /home/pioneerw/public_html/client/include/config.php on line 57

Warning: include(): Failed opening 'config-settings.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/pioneerw/public_html/client/include/config.php on line 57
Unable to connect to DB:Access denied for user 'pioneerw'@'localhost' (using password: NO)

please help

**Comment by Dreamxx** [comment]
so sorry, I left the project for a long time, and  I'm busy now ,I don't think I can help you. sorry! 




At 2016-01-07 02:40:26, "yuvraj131" <notifications@github.com> wrote:



this is the message we are getting on first time page visit:

Warning: include(config-settingsphp): failed to open stream: No such file or directory in /home/pioneerw/public_html/client/include/configphp on line 57

Warning: include(config-settingsphp): failed to open stream: No such file or directory in /home/pioneerw/public_html/client/include/configphp on line 57

Warning: include(): Failed opening 'config-settingsphp' for inclusion (include_path=':/usr/lib/php:/usr/local/lib/php') in /home/pioneerw/public_html/client/include/configphp on line 57
Unable to connect to DB:Access denied for user 'pioneerw'@'localhost' (using password: NO)

please help

**Comment by jethrocarr** [comment]
hi @yuvraj131 ,

Have a read of: https://github.com/jethrocarr/amberdms-bs/blob/master/help/manual/amberdms_billing_system_install_manual.pdf

regards,
Jethro

**Comment by yuvraj131** [comment]
Hi Jethro,

Thank you for your kind support.

Sure, I will go through the attached document and will contact you further,
If I face any issues.

Yuvraj Kumar
