### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by HH-cjh** [jethrocarr/amberdms-bs#8]
How do you install this software??

How do you connect to a db?

There is no guides how to do it.

**Comment by BenzoNZ** [comment]
Installation manual can be found here:

https://github.com/jethrocarr/amberdms-bs/blob/master/help/manual/amberdms_billing_system_install_manual.pdf

**Comment by jethrocarr** [comment]
Have updated the `README.md` to include the link to these docs.
