### ISSUE TITLE
Access to the system ?

### ISSUE THREAD

**Issue by jorgemol** [jethrocarr/amberdms-bs#9]
Greetings.
I have installed it but I have time on the home page, I have turned the database but I do not get an access user.

I saw in the table "users" what seems to me a user and password but the password is encrypted.

----------------------------------------------------------
**Already ready to enter the system**

**Comment by jethrocarr** [comment]
See https://github.com/jethrocarr/amberdms-bs/blob/master/help/manual/amberdms_billing_system_install_manual.pdf

Default username is `setup` password is `setup123`
